routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TravelPackageController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/admin', [DashboardController::class, 'index'])->name('Admin.Dashboard');
Route::resource('PaketTravel', TravelPackageController::class);
Route::resource('GaleriTravel', GalleryController::class);
Route::resource('Transaksi', TransactionController::class);

resources/views/Admin/Transaksi/detail.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Detail Transaksi {{ $item->user->name}}</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="card">
              <div class="card-header border-transparent">
              <table class="table table-bordered">
                <tr>
                  <th>ID</th>
                  <td>{{ $item->id}}</td>
                </tr>
                <tr>
                  <th>Paket Travel</th>
                  <td>{{ $item->travel_package->title}}</td>
                </tr>
                <tr>
                  <th>Pembeli</th>
                  <td>{{ $item->user->name}}</td>
                </tr>
                <tr>
                  <th>Additional Visa</th>
                  <td>Rp.{{ $item->additional_visa}}.000</td>
                </tr>
                <tr>
                  <th>Total Transaksi</th>
                  <td>Rp.{{ $item->transaction_total}}.000</td>
                </tr>
                <tr>
                  <th>Status Transaksi</th>
                  <td>{{ $item->transaction_status}}</td>
                </tr>
                <tr>
                  <th>Pembelian</th>
                  <td>
                    <table class="table table-bordered">
                      <tr>
                        <th>ID</th>
                        <th>Nama</th>
                        <th>Negara</th>
                        <th>Visa</th>
                        <th>Paspor</th>
                      </tr>
                      @foreach ($item->details as $detail)
                          <tr>
                            <td>{{ $detail->id }}</td>
                            <td>{{ $detail->username }}</td>
                            <td>{{ $detail->nationality }}</td>
                            <td>{{ $detail->is_visa ? '30 Hari' : 'N/A' }}</td>
                            <td>{{ $detail->doe_passport }}</td>
                          </tr>
                      @endforeach
                    </table>
                  </td>
                </tr>
              </table>
              </div>
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection

resources/views/Admin/Transaksi/edit.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Edit Status Transaksi</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="card">
              <div class="card-header border-transparent">
                <form method="POST" action="{{ route('Transaksi.update', $item->id) }}">
                @csrf
                @method('PUT')
                    <div class="card-body">
                    <label>Status Transaksi</label>
                    <select name="transaction_status" required class="form-control">
                        <option value="{{ $item->transaction_status}}">
                            Status saat ini ({{ $item->transaction_status }})
                        </option>
                        <option value="IN_CART">In Cart</option>
                        <option value="PENDING">Pending</option>
                        <option value="SUCCESS">Success</option>
                        <option value="CANCEL">Cancel</option>
                        <option value="FAILED">Failed</option>
                    </select>
                        <br>
                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{{route('PaketTravel.index')}}" class="btn btn-primary">Back</a>
                    </div>
                </form>
              </div>
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection

resources/views/Admin/Transaksi/index.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Transaksi Travel</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="admin">Dashboard</a></li>
              <li class="breadcrumb-item active">Transaksi Travel</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <!-- TABLE: LATEST ORDERS -->
        <div class="card">
              <div class="card-header border-transparent">
                <h3 class="card-title">Tabel Transaksi Travel</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
              @if(Session::has('success'))
                <div class="alert alert-light">
                  {{ Session('success') }}
                </div>
              @endif
                <div class="table-responsive">
                  <table class="table m-0" border="1">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>Travel</th>
                      <th>Pengguna</th>
                      <th>Visa</th>
                      <th>Total</th>
                      <th>Status</th>
                      <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($items as $row)    
                    <tr>
                      <td><a href="pages/examples/invoice.html"> {{$row -> id}} </a></td>
                      <td>{{$row -> travel_package -> title}}</td>
                      <td>{{$row -> user -> name}}</td>
                      <td>{{$row -> additional_visa}}</td>
                      <td>{{$row -> transaction_total}}</td>
                      <td>{{$row -> transaction_status}}</td>
                      <td>
                        <div class="sparkbar" data-color="#00a65a" data-height="20">
                        <a class="badge badge-primary" href="{{ route('Transaksi.show', $row->id)}}">Detail</a> |
                        <a class="badge badge-success" href="{{ route('Transaksi.edit', $row->id)}}">Edit Status</a> | 
                        
                        <form action="{{ route('Transaksi.destroy', $row->id) }}" method="POST" class="d-inline">
                        @csrf
                        @method('delete')
                        <button class="badge badge-warning">Hapus</button>
                        </form>

                        </div>
                      </td>
                    </tr>
                    @empty  
                    <tr>
                      <td colspan=6 class="text-center"><i>Data Masih Kosong</i></td>
                    </tr>
                    @endforelse
                    </tbody>
                  </table>
                  </div> 
              </div>
        <!-- /.table-responsive -->
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection