routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TravelPackageController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/admin', [DashboardController::class, 'index'])->name('Admin.Dashboard');
Route::resource('PaketTravel', TravelPackageController::class);
Route::resource('GaleriTravel', GalleryController::class);
Route::resource('Transaksi', TransactionController::class);

resources/views/Admin/PaketTravel/create.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Tambahkan Paket Travel Baru</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="card">
              <div class="card-header border-transparent">
                <form method="POST" action="{{route('PaketTravel.store')}}">
                @csrf
                    <div class="card-body">
                    <label>Judul Travel</label>
                        <input type="text" name="title" required class="form-control" id="text" placeholder="Tambahkan judul travel..." value="{{ old('title')}}">
                        <br>
                    <label>Lokasi Travel</label>
                        <input type="text" name="location" required class="form-control" id="text" placeholder="Lokasi travel..." value="{{ old('location')}}">
                        <br>
                    <label>Deskripsi Travel</label>
                        <textarea name="about" rows="10" required class="d-block w-100 form-control">{{ old('about') }}</textarea>
                        <br>
                    <label>Acara Unggulan</label>        
                        <input type="text" class="form-control" required name="featured_event" placeholder="Featured event" value="{{ old('featured_event')}}">
                        <br>
                    <label>Bahasa</label>
                        <input type="text" class="form-control" required name="language" placeholder="Language" value="{{ old('language')}}">
                        <br>
                    <label>Makanan</label>
                        <input type="text" class="form-control" required name="foods" placeholder="Foods" value="{{ old('foods')}}">
                        <br>
                    <label>Tanggal Keberangkatan</label>
                        <input type="date" class="form-control" required name="departure_date" placeholder="Departure Date" value="{{ old('departure_date')}}">
                        <br>
                    <label>Durasi</label>
                        <input type="text" class="form-control" required name="duration" placeholder="Duration" value="{{ old('duration')}}">
                        <br>
                    <label>Tipe</label>
                        <input type="text" class="form-control" required name="type" placeholder="Tipe Travel..." value="{{ old('type')}}">
                        <br>
                    <label>Harga</label>
                        <input type="number" class="form-control" required name="price" placeholder="Harga Travel..." value="{{ old('price')}}">
                        <br>
                    <label>Bintang</label>
                        <input type="number" class="form-control" required name="star" placeholder="Bintang Travel..." value="{{ old('star')}}">
                        <br>
                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-danger">Reset</button>
                    <a href="{{route('PaketTravel.index')}}" class="btn btn-primary">Back</a>
                    </div>
                </form>
              </div>
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection

resources/views/Admin/PaketTravel/edit.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Perbarui Paket Travel Baru</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="card">
              <div class="card-header border-transparent">
                <form method="POST" action="{{route('PaketTravel.update', $item->id)}}">
                @csrf
                @method('PUT')
                    <div class="card-body">
                    <label>Judul Travel</label>
                        <input type="text" name="title" required class="form-control" id="text" placeholder="Tambahkan judul travel..." value="{{ $item->title }}">
                        <br>
                    <label>Lokasi Travel</label>
                        <input type="text" name="location" required class="form-control" id="text" placeholder="Lokasi travel..." value="{{ $item->location}}">
                        <br>
                    <label>Deskripsi Travel</label>
                        <textarea name="about" rows="10" required class="d-block w-100 form-control">{{ $item->about }}</textarea>
                        <br>
                    <label>Acara Unggulan</label>        
                        <input type="text" class="form-control" required name="featured_event" placeholder="Featured event" value="{{ $item->featured_event}}">
                        <br>
                    <label>Bahasa</label>
                        <input type="text" class="form-control" required name="language" placeholder="Language" value="{{ $item->language}}">
                        <br>
                    <label>Makanan</label>
                        <input type="text" class="form-control" required name="foods" placeholder="Foods" value="{{ $item->foods}}">
                        <br>
                    <label>Tanggal keberangkatan</label>
                        <input type="date" class="form-control" required name="departure_date" placeholder="Departure Date" value="{{ $item->departure_date }}">
                        <br>
                    <label>Durasi</label>
                        <input type="text" class="form-control" required name="duration" placeholder="Duration" value="{{ $item->duration}}">
                        <br>
                    <label>Tipe</label>
                        <input type="text" class="form-control" required name="type" placeholder="Tipe Travel..." value="{{ $item->type}}">
                        <br>
                    <label>Harga</label>
                        <input type="number" class="form-control" required name="price" placeholder="Harga Travel..." value="{{ $item->price}}">
                        <br>
                    <label>Bintang</label>
                        <input type="number" class="form-control" required name="star" placeholder="Bintang Travel..." value="{{ $item->star}}">
                        <br>
                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-danger">Reset</button>
                    <a href="{{route('PaketTravel.index')}}" class="btn btn-primary">Back</a>
                    </div>
                </form>
              </div>
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection

resources/views/Admin/PaketTravel/index.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Paket Travel</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="admin">Dashboard</a></li>
              <li class="breadcrumb-item active">Paket Travel</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <!-- TABLE: LATEST ORDERS -->
        <div class="card">
              <div class="card-header border-transparent">
                <h3 class="card-title">Tabel Paket Travel</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool">
                    <a href="{{route('PaketTravel.create')}}"><i class="fas fa-plus"></i></a>
                  </button>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
              @if(Session::has('success'))
                <div class="alert alert-light">
                  {{ Session('success') }}
                </div>
              @endif
                <div class="table-responsive">
                  <table class="table m-0" border="1">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>Judul</th>
                      <th>Lokasi</th>
                      <th>Tipe</th>
                      <th>Tanggal keberangkatan</th>
                      <th>Harga</th>
                      <th>Bintang</th>  
                      <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($items as $row)
                    <tr>
                      <td><a href="pages/examples/invoice.html"> {{$row -> id}} </a></td>
                      <td>{{$row -> title}}</td>
                      <td>{{$row -> location}}</td>
                      <td>{{$row -> type}}</td>
                      <td>{{$row -> departure_date}}</td>
                      <td>{{$row -> price}}</td>
                      <td>{{$row -> star}}</td>
                      <td>
                        <div class="sparkbar" data-color="#00a65a" data-height="20">
                          <a class="badge badge-success" href="{{route('PaketTravel.edit', $row->id)}}">Edit</a> | 
                          
                          <form action="{{route('PaketTravel.destroy', $row->id)}}" method="POST" class="d-inline">
                          @csrf
                          @method('delete')
                          <button class="badge badge-warning">Hapus</button>
                          </form>

                        </div>
                      </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan=6 class="text-center"><i>Data Masih Kosong</i></td>
                      <td colspan=6 class="text-center"><i>None</i></td>
                    </tr>
                    @endforelse
                    </tbody>
                  </table>
                  </div> 
              </div>
        <!-- /.table-responsive -->
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection