routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TravelPackageController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/admin', [DashboardController::class, 'index'])->name('Admin.Dashboard');
Route::resource('PaketTravel', TravelPackageController::class);
Route::resource('GaleriTravel', GalleryController::class);
Route::resource('Transaksi', TransactionController::class);

resources/views/Admin/GaleriTravel/create.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Tambah Galeri Travel Baru</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="card">
              <div class="card-header border-transparent">

                <form method="POST" action="{{route('GaleriTravel.store')}}" enctype="multipart/form-data">
                @csrf
                    <div class="card-body">

                    <label for="travel_packages_id">Pilih Paket Travel</label>

                    <select name="travel_packages_id" required class="form-control">
                    @foreach($travel_packages as $travel_package)
                        <option value="{{ $travel_package->id}}"> {{ $travel_package->title }}</option>
                    @endforeach
                    </select>
                    <br>

                    <label for="image">Image</label>
                    <input type="file" name="image" class="form-control" required placeholder="Masukan gambar Travel...">
                    <br>

                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-danger">Reset</button>
                    <a href="{{route('GaleriTravel.index')}}" class="btn btn-primary">Back</a>
                    </div>
                </form>
              </div>
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection

resources/views/Admin/GaleriTravel/edit.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Ubah Galeri Travel</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="card">
              <div class="card-header border-transparent">

                <form method="POST" action="{{route('GaleriTravel.update', $item->id)}}" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                    <div class="card-body">

                    <label for="travel_packages_id">Pilih Paket Travel</label>

                    <select name="travel_packages_id" required class="form-control">
                    <option value="{{$item->travel_packages_id}}">Harap teliti sebelum mengubah!</option>
                    @foreach($travel_packages as $travel_package)
                        <option value="{{ $travel_package->id}}"> {{ $travel_package->title }}</option>
                    @endforeach
                    </select>
                    <br>

                    <label for="image">Image</label>
                    <input type="file" name="image" class="form-control" placeholder="Masukan gambar Travel..." required>
                    <br>

                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-danger">Reset</button>
                    <a href="{{route('GaleriTravel.index')}}" class="btn btn-primary">Back</a>
                    </div>
                </form>
              </div>
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection

resources/views/Admin/GaleriTravel/index.blade.php
@extends('layouts.app')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Galeri Travel</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="admin">Dashboard</a></li>
              <li class="breadcrumb-item active">Galeri Travel</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <!-- TABLE: LATEST ORDERS -->
        <div class="card">
              <div class="card-header border-transparent">
                <h3 class="card-title">Tabel Galeri Travel</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool">
                    <a href="{{ route('GaleriTravel.create')}}"><i class="fas fa-plus"></i></a>
                  </button>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
              @if(Session::has('success'))
                <div class="alert alert-light">
                  {{ Session('success') }}
                </div>
              @endif
                <div class="table-responsive">
                  <table class="table m-0" border="1">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>Travel</th>
                      <th>Gambar</th>
                      <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($items as $row)
                    <tr>
                      <td><a href="pages/examples/invoice.html">{{$row -> id}}</a></td>
                      <td>{{$row -> travel_package->title}}</td>
                      <td><img src="{{ Storage::url($row->image)}}" alt="" style="width: 150px;" class="img-thumbnail"/></td>
                      <td>
                        <div class="sparkbar" data-color="#00a65a" data-height="20">
                        <a class="badge badge-success" href="{{ route('GaleriTravel.edit',$row->id)}}">Edit</a> | 
                        
                        <form action="{{ route('GaleriTravel.destroy',$row->id)}}" method="POST" class="d-inline">
                        @csrf
                        @method('delete')
                        <button class="badge badge-warning">Hapus</button>
                        </form>

                        </div>
                      </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan=6 class="text-center"><i>Data Masih Kosong</i></td>
                    </tr>
                    @endforelse
                    </tbody>
                  </table>
                  </div> 
              </div>
        <!-- /.table-responsive -->
        </div>
      <!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
@endsection